type Category {
  id: ID!
  name: String!
}
type SubCategory {
  id: ID!
  name: String!
  categoryId: Category
}

input CategoryInput {
  name: String!
}
input SubCategoryInput {
  name: String!
  categoryId: String!
}

type User {
  id: ID!
  username: String!
  email: String!
  password: String!
  firstName: String!
  lastName: String!
  phone: String!
  gender: String!
  dob: String!
  role: String!
  address: String
  isActive: Boolean
}

input RegisterUserInput {
  username: String!
  email: String!
  password: String!
  firstName: String!
  lastName: String!
  phone: String!
  gender: String!
  dob: String!
  role: String!
  address: String
}


type Product {
  id: ID!
  category: Category
  subCategory: SubCategory
  name: String!
  brand: String!
  stock: String!
  size: String!
  price: String!
  gender: String!
  description: String
  image: String!
}

input RegisterProductInput {
  category: String!
  subCategory: String!
  name: String!
  brand: String!
  stock: String!
  size: String!
  price: String!
  gender: String!
  description: String
  image: String!
}

input EditProductInput {
  category: String!
  subCategory: String!
  name: String!
  brand: String!
  stock: String!
  size: String!
  price: String!
  gender: String!
  description: String
}



type Wishlist {
  id: ID!
  user: User
  product: Product
}

input LoginInput {
  username: String!
  password: String!
}



type Query {
  getCategory: [Category],
  getSubCategory: [SubCategory],
  getUsers: [User],
  getProducts: [Product],
  getOneProduct(id: String!): Product,
  loginAuth(input: LoginInput!): User,
  getSubCategoryByCategoryId(input: String!): [SubCategory] ,
  getFilteredProducts(gender: String, category: String, subCategory: String,
  price: String): [Product!]
  getWishlistByUserId(input: String!): [Wishlist],
      
}

type Mutation {
  
  registerCategory(input: CategoryInput!): Category!,
  registerSubCategory(input: SubCategoryInput!): SubCategory!,
  registerUser(input: RegisterUserInput!): User,
  registerProduct(input: RegisterProductInput!): Product,
  EditProductInput(id: String!, product: EditProductInput!): String,
  removeUser(id: String!): String
  removeProduct(id: String!): String
  deactivateUser(id: String!): String
  addToWishlist(userId: String!, productId: String!): String,
  removeWishlist(id: String!): String
}
